create database aviation_analytics;

use aviation_analytics;

CREATE TABLE Flights (
Year_ INT,
MONTH_ INT,
Day_ INT,
DAY_OF_WEEK INT,
AIRLINE VARCHAR(300),
FLIGHT_NUMBER INT,
TAIL_NUMBER VARCHAR(300),
ORIGIN_AIRPORT VARCHAR(300),
DESTINATION_AIRPORT VARCHAR(300),
SCHEDULED_DEPARTURE INT,
DEPARTURE_TIME VARCHAR(300),
DEPARTURE_DELAY VARCHAR(300),
TAXI_OUT VARCHAR(300),
WHEELS_OFF VARCHAR(300),
SCHEDULED_TIME VARCHAR(300),
ELAPSED_TIME VARCHAR(300),
AIR_TIME VARCHAR(300),
DISTANCE INT,
WHEELS_ON VARCHAR(300),
TAXI_IN VARCHAR(300),
SCHEDULED_ARRIVAL INT,
ARRIVAL_TIME VARCHAR(300),
ARRIVAL_DELAY VARCHAR(300),
DIVERTED INT,
CANCELLED INT,
CANCELLATION_REASON varchar(300),
AIR_SYSTEM_DELAY VARCHAR(300),
SECURITY_DELAY VARCHAR(300),
AIRLINE_DELAY VARCHAR(300),
LATE_AIRCRAFT_DELAY VARCHAR(300),
WEATHER_DELAY VARCHAR(300));

SELECT @@secure_file_priv;

select * from flights;

